version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file: .env

  web:
    build: .
    command: uvicorn api.__main__:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - postgres
    ports:
      - 8008:8000

volumes:
  postgres_db:
